### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by nelas** [nelas/cifonauta#126]
Fix timestamps!

```
Traceback (most recent call last):
  File "./cifonauta.py", line 986, in <module>
    main(sys.argv[1:])
  File "./cifonauta.py", line 915, in main
    query = cbm.search_db(media)
  File "./cifonauta.py", line 85, in search_db
    if record.timestamp != media.timestamp:
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by nelas** [comment]
Already fixed.
